---
# yaml-language-server: $schema=https://schemas.serek.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-ferret
spec:
  dataFrom:
    - extract:
        key: komodo
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-ferret-secret
    template:
      data:
        FERRETDB_POSTGRESQL_URL: "postgres://{{ .dbUser }}:{{ .dbPass }}@komodo-pg-rw.default.svc.cluster.local:5432/komodo"
