---
name: nas
working_dir: ./docker/nas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true
external_secrets:
  EMAIL: "op://home-k8s/caddy/email"
  API_TOKEN: "op://home-k8s/caddy/apiToken"
---
name: exporters
working_dir: ./docker/common/exporters
