---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./namespace.yaml
