---
# yaml-language-server: $schema=https://schemas.serek.xyz/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kguardian
spec:
  hostnames:
    - kguardian.serek.xyz
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: kguardian-frontend
          namespace: flux-system
          port: 5173
      matches:
        - path:
            type: PathPrefix
            value: /
