---
services:
  haproxy:
    container_name: haproxy
    image: haproxy:3.3.3-alpine3.23
    restart: always
    ports:
      - 6443:6443
      - 50000:50000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
