---
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses: ["10.0.20.89"]
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: sovol-zero
  name: sovol-zero-1
---
apiVersion: v1
kind: Service
metadata:
  name: sovol-zero
spec:
  ports:
    - name: moonraker
      port: 7125
    - name: http
      port: 80
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sovol-zero
spec:
  hostnames:
    - sovol-zero.serek.xyz
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: sovol-zero
          port: 7125
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: sovol-zero
          port: 80
      matches:
        - path:
            type: RegularExpression
            value: /webcam[1-3]?/
---
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
  - addresses: ["10.0.20.88"]
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: voron2
  name: voron2-1
---
apiVersion: v1
kind: Service
metadata:
  name: voron2
spec:
  ports:
    - name: moonraker
      port: 7125
    - name: http
      port: 80
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voron2
spec:
  hostnames:
    - voron2.serek.xyz
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: voron2
          port: 7125
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: voron2
          port: 80
      matches:
        - path:
            type: RegularExpression
            value: /webcam[1-3]?/
