---
# yaml-language-server: $schema=https://schemas.serek.xyz/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homestead
spec:
  endpoints:
    - dnsName: "homestead.serek.xyz"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'false'
      recordType: CNAME
      targets: ["ipv4.serek.xyz"]
