---
# yaml-language-server: $schema=https://schemas.serek.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mc-homestead
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 5.1.1
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://schemas.serek.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mc-homestead
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    extraEnv:
      TZ: America/New_York
    extraVolumes:
      - volumeMounts:
          - mountPath: /mnt/backups
            name: nfs
        volumes:
          - name: nfs
            nfs:
              path: /mnt/tank/apps/mc/homestead
              server: 10.0.30.40
    fullnameOverride: *app
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17@sha256:70d953da5bc600632a6b2b468f1f8a9d386cd6142b09985b142522d85c314218
    livenessProbe:
      initialDelaySeconds: 30
    mcbackup:
      backupInterval: 90m
      compressMethod: zstd
      enabled: true
      extraEnv:
        DEST_DIR: /mnt/backups
      image:
        repository: ghcr.io/itzg/mc-backup
        tag: 2026.2.0@sha256:b8c74fe84f6f5caab366a8253466242e1207b09c3e842f47917f645d618a2c4d
    minecraftServer:
      difficulty: normal
      eula: true
      fabricLauncherVersion: "1.1.1"
      gameMode: survival
      jvmXXOpts: "--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
      memory: 10240M
      motd: "Homestead for you."
      onlineMode: true
      ops: "UnworldlyAlex"
      overrideServerProperties: true
      pvp: true
      rcon:
        enabled: true
      spawnProtection: 0
      type: FABRIC
      version: 1.20.1
      viewDistance: 12
      whitelist: "UnworldlyAlex,ManXnTheMoon,The_Windmill,RedMoonCactus,BonezTheMiner"
      worldSaveName: homestead
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    readinessProbe:
      initialDelaySeconds: 30
    resources:
      limits:
        cpu: 4000m
        memory: 12Gi
      requests:
        cpu: 200m
    securityContext:
      fsGroup: 3000
      runAsUser: 3000
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: homestead.serek.xyz
    startupProbe:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: mc-homestead-secret
      targetPath: minecraftServer.rcon.password
      valuesKey: RCON_PASSWORD
