---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: &name node-exporter
spec:
  path: /metrics
  relabelConfigs:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
      - nas.serek.xyz:9100
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: &name smartctl-exporter
spec:
  path: /metrics
  relabelConfigs:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
        - nas.serek.xyz:9633
