---
# yaml-language-server: $schema=https://schemas.serek.xyz/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  metricsPath: /metrics
  relabelings:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
        - nas.serek.xyz:9100
---
# yaml-language-server: $schema=https://schemas.serek.xyz/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl-exporter
spec:
  metricsPath: /metrics
  relabelings:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
        - nas.serek.xyz:9633
