---
# yaml-language-server: $schema=https://schemas.serek.xyz/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
  name: komodo-pg
spec:
  bootstrap:
    # recovery:
    #   source: source
    initdb:
      database: komodo
      owner: komodo
      postInitApplicationSQL:
        - create extension if not exists pg_cron;
        - create extension if not exists documentdb cascade;
  enableSuperuserAccess: true
  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: minio
  #         serverName: komodo-pg-v5
  imageName: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0-ferretdb-2.7.0
  instances: 3
  managed:
    roles:
      - inRoles:
          - documentdb_admin_role
        login: true
        name: komodo
        passwordSecret:
          name: komodo-pg-secret
  monitoring:
    enablePodMonitor: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: minio
        serverName: komodo-pg-v6
  postgresGID: 999
  postgresUID: 999
  postgresql:
    parameters:
      cron.database_name: komodo
      # Copied from https://github.com/FerretDB/documentdb/blob/ferretdb/packaging/10-preload.sh
      documentdb.enableBypassDocumentValidation: "true"
      documentdb.enableCompact: "true"
      documentdb.enableLetAndCollationForQueryMatch: "true"
      documentdb.enableNowSystemVariable: "true"
      documentdb.enableSchemaValidation: "true"
      documentdb.enableSortbyIdPushDownToPrimaryKey: "true"
      documentdb.enableUserCrud: "true"
      documentdb.maxUserLimit: "100"
      max_connections: "300"
      shared_buffers: 512MB
    pg_hba:
      - host komodo postgres localhost trust
      - host komodo komodo localhost trust
    shared_preload_libraries:
      - "pg_cron"
      - "pg_documentdb_core"
      - "pg_documentdb"
  primaryUpdateStrategy: unsupervised
  resources:
    limits:
      cpu: 1
      hugepages-1Gi: 1Gi
      memory: 2Gi
    requests:
      cpu: 1
      hugepages-1Gi: 1Gi
      memory: 2Gi
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: komodo-admin-pg-secret
