---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: komodo
spec:
  cluster:
    name: komodo-pg
  extensions:
    - name: documentdb_core
    - name: pg_cron
    - name: tsm_system_rows
    - name: vector
    - name: postgis
    - name: rum
    - name: documentdb
  name: komodo
  owner: komodo
