---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-admin-pg
spec:
  dataFrom:
    - extract:
        key: cloudnative-pg
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-admin-pg-secret
    template:
      data:
        password: "{{ .pgSuperpass }}"
        s3-access-key: "{{ .s3AccessKey }}"
        s3-secret-key: "{{ .s3SecretKey }}"
        username: "{{ .pgSuperuser}}"
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-pg
spec:
  dataFrom:
    - extract:
        key: komodo
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-pg-secret
    template:
      data:
        password: "{{ .dbPass }}"
        username: "{{ .dbUser }}"
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
