---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../../flux/components/alerts

kind: Kustomization
resources:
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./mainsail/ks.yaml
  - ./node-red/ks.yaml
  - ./rdio-scanner/ks.yaml
  - ./speaches/ks.yaml
  - ./trunk-processor/ks.yaml
  - ./z2m/ks.yaml
  - ./zipline/ks.yaml
  - ./namespace.yaml
