---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: security
resources:
  - ./authelia/ks.yaml
  - ./external-secrets/ks.yaml
  - ./lldap/ks.yaml
  - ./onepass-connect/ks.yaml
  - ./postgres/ks.yaml
  - ./namespace.yaml
