---
# yaml-language-server: $schema=https://schemas.serek.xyz/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-access
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - world
