[[stack]]
name = "nas-exporters"
tags = ["common", "nas"]
[stack.config]
server = "nas"
linked_repo = "home-ops"
run_directory = "docker/common/exporters"

[[stack]]
name = "rdio-exporters"
tags = ["common", "rdio"]
[stack.config]
server = "rdio"
linked_repo = "home-ops"
run_directory = "docker/common/exporters"

[[stack]]
name = "haproxy"
tags = ["nas"]
[stack.config]
server = "nas"
linked_repo = "home-ops"
run_directory = "docker/nas/haproxy"

[[stack]]
name = "pxe"
tags = ["nas"]
[stack.config]
server = "nas"
linked_repo = "home-ops"
run_directory = "docker/nas/pxe"

[[stack]]
name = "registry"
tags = ["nas"]
[stack.config]
server = "nas"
linked_repo = "home-ops"
run_directory = "docker/nas/registry"
