---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-exporter
spec:
  dataFrom:
    - extract:
        key: mktxp
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: mktxp-exporter-secret
    template:
      data:
        CORE_SECRET: "{{ .user }}"
        _mktxp.conf: |
          [MKTXP]
              listen = '0.0.0.0:49090'         # Space separated list of socket addresses to listen to, both IPV4 and IPV6
              socket_timeout = 5

              initial_delay_on_failure = 120
              max_delay_on_failure = 900
              delay_inc_div = 5

              bandwidth = False                   # Turns metrics bandwidth metrics collection on / off
              bandwidth_test_dns_server = 8.8.8.8 # The DNS server to be used for the bandwidth test connectivity check
              bandwidth_test_interval = 600       # Interval for collecting bandwidth metrics
              minimal_collect_interval = 5        # Minimal metric collection interval

              verbose_mode = False                # Set it on for troubleshooting

              fetch_routers_in_parallel = False   # Fetch metrics from multiple routers in parallel / sequentially
              max_worker_threads = 5              # Max number of worker threads that can fetch routers (parallel fetch only)
              max_scrape_duration = 30            # Max duration of individual routers' metrics collection (parallel fetch only)
              total_max_scrape_duration = 90      # Max overall duration of all metrics collection (parallel fetch only)

              persistent_router_connection_pool = True  # Use a persistent router connections pool between scrapes
              persistent_dhcp_cache = True              # Persist DHCP cache between metric collections
              compact_default_conf_values = False       # Compact mktxp.conf, so only specific values are kept on the individual routers' level
              prometheus_headers_deduplication = True   # Deduplicate Prometheus HELP / TYPE headers in the metrics output
        mktxp.conf: |
          [ccr2004]
              hostname = 10.0.30.1

          [crs317]
              hostname = 10.0.30.2

          [hapax2]
              hostname = 10.0.30.5

          [default]
              enabled = True          # turns metrics collection for this RouterOS device on / off
              hostname = localhost    # RouterOS IP address
              port = 8728             # RouterOS IP Port

              username = "{{ .user }}"     # RouterOS user, needs to have 'read' and 'api' permissions
              password = "{{ .password }}"
              credentials_file = ""

              custom_labels = None    # Custom labels to be injected to all device metrics, comma-separated key:value (or key=value) pairs

              use_ssl = False                 # enables connection via API-SSL servis
              no_ssl_certificate = False      # enables API_SSL connect without router SSL certificate
              ssl_certificate_verify = False  # turns SSL certificate verification on / off
              ssl_check_hostname = True       # check if the hostname matches the peer certâ€™s hostname
              ssl_ca_file = ""                # path to the certificate authority file to validate against, leave empty to use system store
              plaintext_login = True          # for legacy RouterOS versions below 6.43 use False

              health = True                   # System Health metrics
              installed_packages = True       # Installed packages
              dhcp = True                     # DHCP general metrics
              dhcp_lease = True               # DHCP lease metrics

              connections = True              # IP connections metrics
              connection_stats = True         # Open IP connections metrics

              interface = True                # Interfaces traffic metrics

              route = True                    # IPv4 Routes metrics
              pool = True                     # IPv4 Pool metrics
              firewall = True                 # IPv4 Firewall rules traffic metrics
              neighbor = True                 # IPv4 Reachable Neighbors
              address_list = None             # Firewall Address List metrics, a comma-separated list of names
              dns = True                      # DNS stats

              ipv6_route = True               # IPv6 Routes metrics
              ipv6_pool = True                # IPv6 Pool metrics
              ipv6_firewall = True            # IPv6 Firewall rules traffic metrics
              ipv6_neighbor = True            # IPv6 Reachable Neighbors
              ipv6_address_list = None        # IPv6 Firewall Address List metrics, a comma-separated list of names

              poe = False                     # POE metrics
              monitor = True                  # Interface monitor metrics
              netwatch = True                 # Netwatch metrics
              public_ip = True                # Public IP metrics
              wireless = True                 # WLAN general metrics
              wireless_clients = True         # WLAN clients metrics
              capsman = True                  # CAPsMAN general metrics
              capsman_clients = True          # CAPsMAN clients metrics
              w60g = False                    # W60G metrics

              eoip = False                    # EoIP status metrics
              gre = False                     # GRE status metrics
              ipip = False                    # IPIP status metrics
              lte = False                     # LTE signal and status metrics (requires additional 'test' permission policy on RouterOS v6)
              ipsec = False                   # IPSec active peer metrics
              switch_port = True              # Switch Port metrics

              kid_control_assigned = False    # Allow Kid Control metrics for connected devices with assigned users
              kid_control_dynamic = False     # Allow Kid Control metrics for all connected devices, including those without assigned user

              user = True                     # Active Users metrics
              queue = True                    # Queues metrics

              bfd = True                       # BFD sessions metrics
              bgp = True                       # BGP sessions metrics
              routing_stats = True             # Routing process stats
              certificate = False             # Certificates metrics

              container = False               # Containers metrics

              remote_dhcp_entry = None        # An MKTXP entry to provide for remote DHCP info / resolution
              remote_capsman_entry = None     # An MKTXP entry to provide for remote capsman info

              use_comments_over_names = True  # when available, forces using comments over the interfaces names
              check_for_updates = False       # check for available ROS updates
      engineVersion: v2
