---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zipline
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 1h
  values:
    controllers:
      zipline:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              CORE_DEFAULT_DOMAIN: zl.serek.xyz
              CORE_PORT: &port 80
              CORE_RETURN_HTTPS_URLS: true
              DATASOURCE_S3_BUCKET: zipline
              DATASOURCE_S3_ENDPOINT: https://s3.serek.xyz
              DATASOURCE_S3_FORCE_PATH_STYLE: true
              DATASOURCE_S3_PORT: 443
              DATASOURCE_S3_REGION: us-east-1
              DATASOURCE_S3_USE_SSL: true
              DATASOURCE_TYPE: s3
              FEATURES_OAUTH_REGISTRATION: true
              FEATURES_ROBOTS_TXT: false
              FEATURES_USER_REGISTRATION: false
              FEATURES_VERSION_CHECKING: false
              FILES_DEFAULT_EXPIRATION: ""
              FILES_DEFAULT_FORMAT: uuid
              FILES_DISABLED_EXTENSIONS: ps1,pdf,bat,exe,sh,fish
              FILES_LENGTH: 12
              FILES_MAX_FILE_SIZE: 1gb
              FILES_REMOVE_GPS_METADATA: true
              FILES_ROUTE: /up
              INVITES_ENABLED: false
              OAUTH_BYPASS_LOCAL_LOGIN: true
              OAUTH_LOGIN_ONLY: true
              OAUTH_OIDC_AUTHORIZE_URL: https://sso.serek.xyz/api/oidc/authorization
              OAUTH_OIDC_REDIRECT_URI: https://zl.serek.xyz/api/auth/oauth/oidc
              OAUTH_OIDC_TOKEN_URL: https://sso.serek.xyz/api/oidc/token
              OAUTH_OIDC_USERINFO_URL: https://sso.serek.xyz/api/oidc/userinfo
              TZ: America/New_York
              URLS_LENGTH: 6
              URLS_ROUTE: /go
            envFrom:
              - secretRef:
                  name: zipline-secret
            image:
              repository: ghcr.io/diced/zipline
              tag: 4.4.0@sha256:a85bc04e5b160059ebdc2812e3a3de9fc777a226573607929910a7f447426796
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /api/healthcheck
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
            resources:
              limits:
                memory: 6Gi
              requests:
                cpu: 1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
    persistence:
      tmpfs:
        globalMounts:
          - path: /tmp
        type: emptyDir
    route:
      app:
        hostnames:
          - zl.serek.xyz
        parentRefs:
          - name: envoy-external
            namespace: network
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
