---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.11.23
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  values:
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
    server:
      extraArgs:
        syslog.extraFields.udp: '{"source":"syslog"}'
        syslog.listenAddr.udp: :5140
        syslog.tenantID.udp: 0:1
        syslog.useRemoteIP.udp: true
      fullnameOverride: victoria-logs
      persistentVolume:
        enabled: true
        size: 50Gi
        storageClassName: ceph-block
      retentionPeriod: 30d
      route:
        enabled: true
        extraRules:
          - filters:
              - requestRedirect:
                  path:
                    replaceFullPath: /select/vmui/
                    type: ReplaceFullPath
                  statusCode: 302
                type: RequestRedirect
            matches:
              - path:
                  type: Exact
                  value: /
        hostnames:
          - logs.serek.xyz
        parentRefs:
          - name: envoy-internal
            namespace: network
      serviceMonitor:
        enabled: true
