apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  commonName: root-ca.internal.serek.xyz
  duration: 87600h
  isCA: true
  issuerRef:
    name: selfsigned-issuer
  privateKey:
    algorithm: Ed25519
  secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-ca-issuer
spec:
  ca:
    secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca
spec:
  commonName: intermediate-ca.internal.serek.xyz
  duration: 8760h
  isCA: true
  issuerRef:
    name: root-ca-issuer
  privateKey:
    algorithm: Ed25519
  secretName: intermediate-ca-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: intermediate-ca-issuer
spec:
  ca:
    secretName: intermediate-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-client
spec:
  dnsNames:
    - "test-client.default.svc.cluster.local"
    - "test-client"
  isCA: false
  issuerRef:
    name: intermediate-ca-issuer
  secretName: test-client
  usages:
    - server auth
    - client auth
