apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  isCA: true
  duration: 87600h
  commonName: root-ca.internal.serek.xyz
  secretName: root-ca-secret
  privateKey:
    algorithm: Ed25519
  issuerRef:
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-ca-issuer
spec:
  ca:
    secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: intermediate-ca
spec:
  isCA: true
  duration: 8760h
  commonName: intermediate-ca.internal.serek.xyz
  secretName: intermediate-ca-secret
  privateKey:
    algorithm: Ed25519
  issuerRef:
    name: root-ca-issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: intermediate-ca-issuer
spec:
  ca:
    secretName: intermediate-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: generated-cert
spec:
  duration: 8760h
  commonName: generated.internal.serek.xyz
  secretName: generated-secret
  privateKey:
    algorithm: Ed25519
  issuerRef:
    name: intermediate-ca-issuer
