---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo
spec:
  dataFrom:
    - extract:
        key: komodo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "komodo_$1"
    - extract:
        key: authelia
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authelia_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-secret
    template:
      data:
        KOMODO_DATABASE_PASSWORD: "{{ .komodo_dbPass }}"
        KOMODO_DATABASE_USERNAME: "{{ .komodo_dbUser }}"
        KOMODO_OIDC_CLIENT_SECRET: "{{ .authelia_komodoSecret }}"
      engineVersion: v2
