---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo
spec:
  dataFrom:
    - extract:
        key: komodo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "komodo_$1"
    - extract:
        key: authelia
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authelia_$1"
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-secret
    template:
      data:
        KOMODO_DATABASE_PASSWORD: "{{ .komodo_dbPass }}"
        KOMODO_DATABASE_USERNAME: "{{ .komodo_dbUser }}"
        KOMODO_OIDC_CLIENT_SECRET: "{{ .authelia_komodoSecret }}"
      engineVersion: v2
---
# yaml-language-server: $schema=https://schemas.serek.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo-config
spec:
  dataFrom:
    - extract:
        key: komodo
    - extract:
        key: authelia
        property: komodoSecret
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-config-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
              - key: config.toml
                templateAs: Values
            name: komodo-config-tpl
          target: Data
