---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo
spec:
  dataFrom:
    - extract:
        key: komodo
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-secret
    template:
      data:
        KOMODO_DATABASE_PASSWORD: "{{ .dbPass }}"
        KOMODO_DATABASE_USERNAME: "{{ .dbUser }}"
      engineVersion: v2
