---
# yaml-language-server: $schema=https://schemas.serek.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komodo
spec:
  dataFrom:
    - extract:
        key: komodo
    - extract:
        key: authelia
        property: komodoSecret
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: komodo-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
              - key: config.toml
                templateAs: Values
            name: komodo-config-tpl
          target: Data
