---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: observability
resources:
  - ./namespace.yaml
  - ./fluent-bit/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./keda/ks.yaml
  - ./kromgo/ks.yaml
  - ./mktxp-exporter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./victoria-metrics/ks.yaml
