---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../flux/components/alerts
kind: Kustomization
namespace: observability
resources:
  - ./fluent-bit/ks.yaml
  - ./gatus/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./namespace.yaml
  - ./snmp-exporter/ks.yaml
  - ./kromgo/ks.yaml
  - ./victoria-logs/ks.yaml
