---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: flux-system
resources:
  - ./flux-operator/ks.yaml
  - ./namespace.yaml
  - ./flux-instance/ks.yaml
