---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: actions-runner-system
resources:
  - ./namespace.yaml
  - ./actions-runner-controller/ks.yaml
