---
# yaml-language-server: $schema=https://schemas.serek.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trunk-processor
spec:
  dataFrom:
    - extract:
        key: trunk-processor
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepass-connect
  target:
    name: trunk-processor-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .s3AccessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3SecretKey }}"
        DATABASE_URL: "postgres://{{ .dbUser }}:{{ .dbPass }}@postgres16-rw.database.svc.cluster.local:5432/trunk-processor"
        DISCORD_WEBHOOK: "{{ .discordWebhook }}"
        FILTER_TG_GROUP: "{{ .filterGroup }}"
        FILTER_TG_ID: "{{ .filterTgId }}"
