---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: octodns-preview

on:
  pull_request_target:
    branches: ["main"]
    paths:
      - octodns/**
      - .github/workflows/octodns*.yaml

jobs:
  octodns-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7
      - name: Install the project
        run: uv sync --extra octodns
      - name: Validate octodns config
        env:
          OCTODNS_CF_TOKEN: placeholder
        run: |
          uv run octodns-validate --config-file=./octodns/config.yaml --all
  octodns-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install uv
        uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7
      - name: Install the project
        run: uv sync --extra octodns
      - name: Load secret
        uses: 1password/load-secrets-action@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OCTODNS_CF_TOKEN: op://home-k8s/octodns/cfToken
      - name: Preview octodns config
        run: |
          uv run octodns-sync --config-file=./octodns/config.yaml | tee octodns-preview.md
      - name: Generate Github preview
        id: preview
        run: |
          cat octodns-preview.md
          echo "preview<<EOF" >> $GITHUB_OUTPUT
          cat octodns-preview.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Add comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-failure: Diff was not successful
          message: |
            ${{ steps.preview.outputs.preview }}
