---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./ddns/ks.yaml
  - ./echo-server/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-dns/ks.yaml
  - ./multus/ks.yaml
