---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../flux/components/alerts
kind: Kustomization
namespace: network
resources:
  - ./cert-manager/ks.yaml
  - ./ddns/ks.yaml
  - ./multus/ks.yaml
  - ./external-dns/ks.yaml
  - ./echo-server/ks.yaml
  - ./namespace.yaml
  - ./ingress-nginx/ks.yaml
