---
apiVersion: kustomize.config.k8s.io/v1beta1
components:
  - ../../components/alerts
kind: Kustomization
namespace: storage
resources:
  - ./namespace.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
